version: '3.4'

services:
  catalogdb:
    image: mongo
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/Ocelot.ApiGateway/Dockerfile  
   
volumes:
  mongo_data:
  elasticsearch-data:


